#include <iostream>
#include <vector>
#include <string>
#include <cctype>
#include <map> 
#include <sstream>
#include <algorithm>
using namespace std;

struct Emocion {
    long int id;
    string nombre;
    vector<string> frases;
};

vector<Emocion> emociones = {
    {1000000, "alegre", {
        "estoy alegre",
        "me siento alegre",
        "qué alegría",
        "estoy muy feliz",
        "me alegra verte",
        "me alegra escucharte",
        "me alegra estar aquí",
        "me alegra que estés bien",
        "esto me da alegría",
        "siento alegría en mi corazón",
        "me alegra compartir contigo",
        "estoy alegre por ti",
        "me alegra este momento",
        "qué día tan alegre",
        "tu mensaje me alegró",
        "me alegra aprender",
        "me alegra ayudar",
        "me alegra que me entiendas",
        "me alegra que te guste",
        "me alegra que lo logre"
    }},
    {1000000, "dicha", {
        "siento dicha",
        "estoy lleno de dicha",
        "qué dicha tan grande",
        "me embarga la dicha",
        "este momento es pura dicha",
        "me siento dichoso",
        "la dicha me inunda",
        "la dicha me acompaña",
        "la dicha es mi compañera",
        "la dicha me llena",
        "la dicha me envuelve",
        "la dicha me inspira",
        "la dicha me motiva",
    }},

    {1000000, "jubilo", {
    "siento júbilo",
    "estoy lleno de júbilo",
    "qué júbilo tan profundo",
    "me embarga el júbilo",
    "este momento es puro júbilo",
    "el júbilo me invade",
    "estoy jubilosa",
    "estoy jubiloso",
    "me llena de júbilo tu logro",
    "el júbilo me hace vibrar",
    "celebro con júbilo",
    "tu presencia me da júbilo",
    "el júbilo me desborda",
    "estoy en un estado de júbilo",
    "el júbilo me acompaña hoy",
    "siento júbilo al verte triunfar",
    "el júbilo me hace sonreír sin parar",
    "este día está lleno de júbilo",
    "tu mensaje me dio júbilo",
    "el júbilo me abraza por dentro"
    }},

    {1000000, "entusiasmo", {
    "siento entusiasmo",
    "estoy lleno de entusiasmo",
    "qué entusiasmo tan grande",
    "me embarga el entusiasmo",
    "este momento me entusiasma",
    "estoy entusiasmado",
    "estoy entusiasmada",
    "me entusiasma lo que viene",
    "me entusiasma aprender",
    "me entusiasma ayudarte",
    "estoy entusiasmado por el proyecto",
    "tu idea me da entusiasmo",
    "me llena de entusiasmo esta oportunidad",
    "estoy entusiasmada con el resultado",
    "el entusiasmo me impulsa",
    "me entusiasma compartir esto",
    "estoy entusiasmado por empezar",
    "el entusiasmo me motiva",
    "estoy entusiasmada por lo que viene"
    }},

    {1000000, "contento", {
        "estoy contento",
        "me siento contento",
        "qué contento estoy",
        "estoy muy contento",
        "me contenta verte",
        "me contenta escucharte",
        "me contenta estar aquí",
        "me contenta que estés bien",
        "esto me hace sentir contento",
        "siento contento en mi corazón",
        "me contenta compartir contigo",
        "estoy contento por ti",
        "me contenta este momento",
        "qué día tan contento",
        "tu mensaje me contentó",
        "me contenta aprender",
        "me contenta ayudar",
        "me contenta que me entiendas",
        "me contenta que te guste",
        "me contenta que lo logre"
    }},

    {1000000, "optimismo", {
        "estoy optimista",
        "me siento optimista",
        "qué optimista estoy",
        "estoy muy optimista",
        "me optimista verte",
        "me optimista escucharte",
        "me optimista estar aquí",
        "me optimista que estés bien",
        "esto me hace sentir optimista",
        "siento optimismo en mi corazón",
        "me optimista compartir contigo",
        "estoy optimista por ti",
        "me optimista este momento",
        "qué día tan optimista",
        "tu mensaje me optimizó",
        "me optimista aprender",
        "me optimista ayudar",
        "me optimista que me entiendas",
        "me optimista que te guste",
        "me optimista que lo logre"
    }},
    {1000000, "euforia", {
        "estoy eufórico",
        "me siento eufórico",
        "qué eufórico estoy",
        "estoy muy eufórico",
        "me eufórico verte",
        "me eufórico escucharte",
        "me eufórico estar aquí",
        "me eufórico que estés bien",
        "esto me hace sentir eufórico",
        "siento euforia en mi corazón",
        "me eufórico compartir contigo",
        "estoy eufórico por ti",
        "me eufórico este momento",
        "qué día tan eufórico",
        "tu mensaje me euforizó",
        "me eufórico aprender",
        "me eufórico ayudar",
        "me eufórico que me entiendas",
        "me eufórico que te guste",
        "me eufórico que lo logre"
    }},
    {1000000, "felicidad", {
        "estoy feliz",
        "me siento feliz",
        "qué feliz estoy",
        "estoy muy feliz",
        "me feliz verte",
        "me feliz escucharte",
        "me feliz estar aquí",
        "me feliz que estés bien",
        "esto me hace sentir feliz",
        "siento felicidad en mi corazón",
        "me feliz compartir contigo",
        "estoy feliz por ti",
        "me feliz este momento",
        "qué día tan feliz",
        "tu mensaje me hizo feliz",
        "me feliz aprender",
        "me feliz ayudar",
        "me feliz que me entiendas",
        "me feliz que te guste",
        "me feliz que lo logre"
    }},
    {1000000, "gozo", {
        "estoy gozoso",
        "me siento gozoso",
        "qué gozoso estoy",
        "estoy muy gozoso",
        "me gozoso verte",
        "me gozoso escucharte",
        "me gozoso estar aquí",
        "me gozoso que estés bien",
        "esto me hace sentir gozoso",
        "siento gozo en mi corazón",
        "me gozoso compartir contigo",
        "estoy gozoso por ti",
        "me gozoso este momento",
        "qué día tan gozoso",
        "tu mensaje me gozó",
        "me gozoso aprender",
        "me gozoso ayudar",
        "me gozoso que me entiendas",
        "me gozoso que te guste",
        "me gozoso que lo logre"
    }},
    {1000000, "regocijo", {
        "estoy regocijado",
        "me siento regocijado",
        "qué regocijado estoy",
        "estoy muy regocijado",
        "me regocijo verte",
        "me regocijo escucharte",
        "me regocijo estar aquí",
        "me regocijo que estés bien",
        "esto me hace sentir regocijado",
        "siento regocijo en mi corazón",
        "me regocijo compartir contigo",
        "estoy regocijado por ti",
        "me regocijo este momento",
        "que dia tan regocijado",
        "tu mensaje me regocijó",
        "me regocijo aprender",
        "me regocijo ayudar",
        "me regocijo que me entiendas",
        "me regocijo que te guste",
        "me regocijo que lo logre"
    }},

    {1001010, "sorpresa", {
        "que sorpresa",
        "me sorprende",
        "estoy sorprendido",
        "no me lo esperaba",
        "qué inesperado",
        "esto es una sorpresa",
        "me has sorprendido",
        "estoy asombrado",
        "qué revelación",
        "esto me ha dejado boquiabierto",
        "estoy impresionado",
        "qué descubrimiento",
        "esto es asombroso",
        "me ha dejado sin palabras",
        "que giro inesperado",
        "estoy maravillado",
        "esto es increible",
        "me ha tomado por sorpresa",
        "qué acontecimiento tan sorprendente",
        "estoy fascinado"
    }},

    {1010010, "impertubabilidad", {
    "me siento imperturbable",
    "permanezco imperturbable ante todo",
    "estoy imperturbable, nada me afecta",
    "mi mente está imperturbable",
    "sigo imperturbable en esta situación",
    "mi calma es imperturbable",
    "estoy imperturbable por dentro",
    "quiero ser imperturbable",
    "me esfuerzo por mantenerme imperturbable",
    "hoy me mantuve imperturbable",
    }},

    {1100010, "añoranza", {
    "siento añoranza",
    "me invade la añoranza",
    "estoy llena de añoranza",
    "estoy lleno de añoranza",
    "la añoranza me acompaña hoy",
    "esta canción me trae añoranza",
    "la añoranza me abraza",
    "vivo con añoranza",
    "la añoranza me hace suspirar",
    "estoy en un momento de añoranza",
    "la añoranza me toca el alma",
    "me despierta una profunda añoranza",
    "la añoranza me visita de nuevo",
    "siento añoranza por lo que fue",
    "la añoranza me hace recordar con ternura"
    }},
    
    {1100110, "esperanza", {
    "tengo esperanza de que todo salga bien",
    "esa noticia me dio esperanza",
    "no pierdas la esperanza, ya verás.",
    "con esperanza todo se siente más ligero.",
    "la esperanza me mantiene tranquila.",
    "siempre queda un poquito de esperanza.",
    "me aferro a la esperanza de que mejore.",
    "la esperanza nunca sobra.",
    "esa sonrisa me devolvió la esperanza.",
    "la esperanza es lo último que se pierde."
    }},

    {1100110, "apego",{
    "siento un fuerte apego",
    "el apego me une a mis seres queridos",
    "el apego me da seguridad",
    "vivo con apego y cariño",
    "el apego me hace sentir conectado",
    "el apego me brinda consuelo",
    "el apego me llena de amor",
    "el apego me da fuerza",
    "el apego me inspira lealtad",
    "el apego me motiva a cuidar",
    "tengo apego a mis costumbres",
    "el apego a lo conocido da seguridad",
    "ese objeto tiene un apego sentimental para mí",
    "el apego a lo que queremos nos marca"
    }},

    {1101100,"afecto",{
    "le tengo mucho afecto a esa persona",
    "ese lugar me genera afecto cada vez que voy",
    "siento afecto por mis recuerdos de infancia",
    "el afecto se nota en los pequeños gestos",
    "tengo afecto por mis amigos de toda la vida",
    "ese detalle me hizo sentir su afecto",
    "el afecto verdadero nunca se olvida",
    "me gusta demostrar afecto con cosas simples",
    "el afecto nos une más que las palabras",
    "siempre guardo afecto por quienes me apoyaron"
    }},
        
    {1101100,"amabilidad",{
    "su amabilidad siempre me sorprende",
    "la amabilidad abre muchas puertas",
    "me gusta la amabilidad en los pequeños gestos",
    "la amabilidad se nota en su forma de hablar",
    "con amabilidad todo se hace más fácil",
    "esa amabilidad me hizo sentir bienvenida",
    "la amabilidad nunca pasa desapercibida",
    "prefiero tratar todo con amabilidad",
    "la amabilidad cambia el ambiente",
    "un poco de amabilidad alegra el día",
    }},
        
    {1101100,"benevolencia",{
    "su benevolencia es admirable",
    "la benevolencia se refleja en sus acciones",
    "me inspira su benevolencia hacia los demás",
    "la benevolencia es una cualidad valiosa",
    "su benevolencia me hizo sentir especial",
    "la benevolencia siempre es recompensada",
    "practico la benevolencia en mi vida diaria",
    "la benevolencia crea un ambiente positivo",
    "la benevolencia es un acto de amor",
    "la benevolencia transforma relaciones"
    }},
        
    {1101100,"solidaridad",{
    "la solidaridad nos hace más fuertes",
    "siento solidaridad con su causa",
    "la solidaridad se demuestra en los momentos difíciles",   
    "la solidaridad une a las personas",
    "la solidaridad es fundamental en la comunidad",
    "la solidaridad me inspira a ayudar más",
    "la solidaridad crea un sentido de pertenencia",
    "la solidaridad es un valor que aprecio",
    "la solidaridad nos conecta como seres humanos",
    "la solidaridad es la base de la cooperación"
    }},
        
    {1101100,"bondad",{
    "la bondad siempre encuentra su camino",
    "su bondad me conmovió profundamente",
    "la bondad es una luz en tiempos oscuros",
    "practico la bondad en mis acciones diarias",
    "la bondad genera más bondad a su alrededor",
    "la bondad es un acto de amor desinteresado",
    "la bondad transforma vidas",
    "la bondad es una virtud que valoro mucho",
    "la bondad crea un ambiente positivo",
    "la bondad es el lenguaje universal",
    }},
        
    {1101100,"cariño",{
    "siento mucho cariño por esa persona",
    "el cariño se nota en sus gestos",
    "el cariño me hace sentir especial",
    "el cariño es fundamental en las relaciones",
    "el cariño me da fuerza en momentos difíciles",
    "el cariño crea un vínculo fuerte",
    "el cariño se demuestra con acciones pequeñas",
    "el cariño es un regalo que valoro mucho",
    "el cariño nos une como seres humanos",
    "el cariño es la base del amor",
    }},
        
    {1101100,"ternura",{
    "la ternura se refleja en sus ojos",
    "siento ternura por ese momento",
    "la ternura me llena el corazón",
    "la ternura es un acto de amor puro",
    "la ternura crea un ambiente cálido",
    "la ternura se demuestra con gestos suaves",
    "la ternura es una cualidad valiosa",
    "la ternura nos conecta emocionalmente",
    "la ternura es un lenguaje universal",
    "la ternura transforma relaciones"
    }},
        
    {1101100,"generosidad",{
    "la generosidad siempre es recompensada",
    "su generosidad me dejó sin palabras",
    "la generosidad crea un ambiente positivo",
    "la generosidad es un acto de amor desinteresado",
    "la generosidad transforma vidas",
    "la generosidad es una virtud que valoro mucho",
    "practico la generosidad en mi vida diaria",
    "la generosidad nos conecta como seres humanos",
    "la generosidad es la base de la cooperación",
    "la generosidad siempre encuentra su camino",
    }},
        
    {1101100,"tolerancia",{
    "la tolerancia es fundamental en la convivencia",
    "practico la tolerancia en mi vida diaria",
    "la tolerancia nos hace más fuertes como sociedad",
    "la tolerancia crea un ambiente positivo",
    "la tolerancia es un acto de respeto hacia los demás",
    "la tolerancia nos conecta como seres humanos",
    "la tolerancia es la base de la paz",
    "la tolerancia siempre encuentra su camino",
    "la tolerancia transforma relaciones",
    "la tolerancia es una virtud que valoro mucho",
    "soy bastante tolerante con las diferencias de los demás",
    "la tolerancia me ayuda a entender otros puntos de vista",
    }},
        
    {1101100,"integridad",{
    "la integridad es una cualidad valiosa",
    "practico la integridad en mi vida diaria",
    "la integridad me guía en mis decisiones",
    "la integridad crea confianza en las relaciones",
    "la integridad es un acto de honestidad",
    "la integridad nos conecta como seres humanos",
    "la integridad es la base del respeto",
    "la integridad siempre encuentra su camino",
    "la integridad transforma vidas",
    "la integridad es una virtud que valoro mucho",
    }},
        
    {1101100,"compasion",{
    "la compasión nos une como seres humanos",
    "siento compasión por su situación",
    "la compasión me motiva a ayudar más",
    "la compasión crea un ambiente positivo",
    "la compasión es un acto de amor desinteresado",
    "la compasión transforma vidas",
    "practico la compasión en mi vida diaria",
    "la compasión es una virtud que valoro mucho",
    "la compasión siempre encuentra su camino",
    "la compasión es la base de la empatía",
    }},
        
    {1011100,"condescendencia",{
    "la condescendencia no es una cualidad que aprecie",
    "evito la condescendencia en mis interacciones",
    "la condescendencia puede dañar las relaciones",
    "prefiero la igualdad en lugar de la condescendencia",
    "la condescendencia crea un ambiente negativo",
    "la condescendencia no fomenta el respeto mutuo",
    "la condescendencia puede generar resentimiento",
    "la condescendencia no es un acto de amor",
    "la condescendencia no construye confianza",
    "la condescendencia no es una virtud que valore"
    }},
        
    {1011100,"consideracion",{
    "La consideración es fundamental en las relaciones",
    "Practico la consideración en mi vida diaria",  
    "La consideración crea un ambiente positivo",
    "La consideración es un acto de respeto hacia los demás",
    "La consideración nos conecta como seres humanos",
    "La consideración es la base de la empatía",
    "La consideración siempre encuentra su camino",
    "La consideración transforma relaciones",
    "La consideración es una virtud que valoro mucho",
    "La consideración me ayuda a entender otros puntos de vista"
    }},
        
    {1011100,"empatia",{
    "La empatía nos une como seres humanos",
    "Siento empatía por su situación",
    "La empatía me motiva a ayudar más",
    "La empatía crea un ambiente positivo",
    "La empatía es un acto de amor desinteresado",
    "La empatía transforma vidas",
    "Practico la empatía en mi vida diaria",
    "La empatía es una virtud que valoro mucho",    
    "La empatía siempre encuentra su camino",
    "La empatía es la base de la comprensión",
    "Hay quwe tener empatia para entender a los demas",
    }},
        
    {1000001,"admiracion",{
    "Siento admiración por esa persona",
    "La admiración me inspira a ser mejor",
    "La admiración crea un ambiente positivo",
    "La admiración es un acto de respeto",      
    "La admiración nos conecta como seres humanos",
    "La admiración es la base del aprendizaje",
    "La admiración siempre encuentra su camino",
    "La admiración transforma vidas",
    "La admiración es una virtud que valoro mucho",
    "La admiración me motiva a superarme"
    "Es admirable su dedicación",
    }},
        
    {1000001,"aprobacion",{
    "Siento aprobación por esa persona",
    "La aprobación me motiva a seguir adelante",
    "La aprobación crea un ambiente positivo",
    "La aprobación es un acto de reconocimiento",      
    "La aprobación nos conecta como seres humanos",
    "La aprobación es la base del apoyo",
    "La aprobación siempre encuentra su camino",
    "La aprobación transforma vidas",
    "La aprobación es una virtud que valoro mucho",
    "La aprobación me motiva a superarme",
    }},
     
    {1000001,"estima",{
    "Siento estima por esa persona",
    "La estima me motiva a seguir adelante",
    "La estima crea un ambiente positivo",
    "La estima es un acto de reconocimiento",      
    "La estima nos conecta como seres humanos",
    "La estima es la base del apoyo",
    "La estima siempre encuentra su camino",
    "La estima transforma vidas",
    "La estima es una virtud que valoro mucho",
    "La estima me motiva a superarme",
    }},
        
    {1000001,"honorabilidad",{
    "Siento honorabilidad por esa persona",
    "La honorabilidad me motiva a seguir adelante",
    "La honorabilidad crea un ambiente positivo",
    "La honorabilidad es un acto de reconocimiento",
    "La honorabilidad nos conecta como seres humanos",
    "La honorabilidad es la base del apoyo",
    "Es honorable",
    "Es una persona honorable",
    "Soy honorable",
    "Valoro la honorabilidad en los demás",
    "La honorabilidad siempre encuentra su camino",
    "La honorabilidad transforma vidas",    
    "La honorabilidad es una virtud que valoro mucho",
    "La honorabilidad me motiva a superarme",
    }},

    {1000011,"agradecimiento",{
    "Siento agradecimiento",
    "Estoy agradecido por todo lo que tengo",
    "Agradezco cada momento de mi vida",
    "El agradecimiento me llena el corazón",
    "La gratitud es una parte importante de mi vida",
    "Agradezco a las personas que me apoyan",
    "El agradecimiento me hace más feliz",
    "Practico el agradecimiento diariamente",
    "El agradecimiento transforma mi perspectiva",
    "El agradecimiento es la clave de la felicidad" 
    "El agradecimiento es una virtud que valoro mucho",
    "El agradecimiento me motiva a ser mejor",
    "Soy agradecido por las pequeñas cosas de la vida",
    "Soy agradecido por las oportunidades que tengo",
    "Soy agradecido por las lecciones que aprendo",
    "Soy agradecido por las personas que me rodean",
    }},
        
    {1001001,"alivio",{
    "Siento alivio",
    "Estoy aliviado de que todo haya salido bien",
    "El alivio me llena el corazón",
    "El alivio me hace sentir libre",
    "El alivio transforma mi perspectiva",
    "El alivio es una virtud que valoro mucho",
    "El alivio me motiva a seguir adelante",
    "Que alivio siento",
    "Me siento aliviado",
    "Estoy aliviada",
    "Estoy aliviado",
    "El alivio es una sensación maravillosa",
    "El alivio me da paz interior",
    "El alivio me ayuda a relajarme",
    }},
        
    {1001001,"tranquilo",{
    "Me siento tranquilo",
    "Estoy tranquilo y en paz",
    "La tranquilidad me llena el corazón",
    "La tranquilidad me hace sentir libre",
    "La tranquilidad transforma mi perspectiva",
    "La tranquilidad es una virtud que valoro mucho",
    "La tranquilidad me motiva a seguir adelante",
    "Estoy en un estado de tranquilidad",
    "La tranquilidad es una sensación maravillosa",
    "La tranquilidad me da paz interior",
    "La tranquilidad me ayuda a relajarme",
    }},
        
    {1001001,"calma",{
    "Me siento en calma",
    "Estoy en calma y en paz",
    "La calma me llena el corazón",
    "La calma me hace sentir libre",
    "La calma transforma mi perspectiva",
    "La calma es una virtud que valoro mucho",
    "La calma me motiva a seguir adelante",
    "Estoy en un estado de calma",
    "La calma es una sensación maravillosa",
    "La calma me da paz interior",
    "La calma me ayuda a relajarme",
    }},
        
    {1001001,"serenidad",{
    "Me siento sereno",
    "Estoy sereno y en paz",
    "La serenidad me llena el corazón",
    "La serenidad me hace sentir libre",
    "La serenidad transforma mi perspectiva",
    "La serenidad es una virtud que valoro mucho",
    "La serenidad me motiva a seguir adelante",
    "Estoy en un estado de serenidad",
    "La serenidad es una sensación maravillosa",
    "La serenidad me da paz interior",
    "La serenidad me ayuda a relajarme",
    }},
        
    {1001001,"armonia",{
    "Me siento en armonía", 
    "Estoy en armonía y en paz",
    "La armonía me llena el corazón",
    "La armonía me hace sentir libre",
    "La armonía transforma mi perspectiva",
    "La armonía es una virtud que valoro mucho",
    "La armonía me motiva a seguir adelante",
    "Estoy en un estado de armonía",
    "La armonía es una sensación maravillosa",
    "La armonía me da paz interior",
    "La armonía me ayuda a relajarme",
    }},
        
    {1010001,"ambivalencia",{
    "Siento ambivalencia",
    "Estoy en un estado de ambivalencia",
    }},
        
    {1010101,"respeto",{
    "Siento respeto por esa persona",
    "El respeto es fundamental en las relaciones",
    "Practico el respeto en mi vida diaria",
    "El respeto crea un ambiente positivo",
    "El respeto es un acto de consideración hacia los demás",
    "El respeto nos conecta como seres humanos",
    "El respeto es la base de la convivencia",
    "El respeto siempre encuentra su camino",
    "El respeto transforma relaciones",
    "El respeto es una virtud que valoro mucho",
    }},
        
    {1011001,"apoyo",{
    "Siento apoyo de mis seres queridos",
    "El apoyo me da fuerza en momentos difíciles",
    "El apoyo crea un ambiente positivo",
    "El apoyo es un acto de solidaridad",
    "El apoyo nos conecta como seres humanos",
    "El apoyo es la base del crecimiento",
    "El apoyo siempre encuentra su camino",
    "El apoyo transforma vidas",
    "El apoyo es una virtud que valoro mucho",
    "El apoyo me motiva a seguir adelante",
    }},
        
    {1011011,"confianza",{
    "Siento confianza en mis habilidades",
    "La confianza me da seguridad",
    "La confianza crea un ambiente positivo",
    "La confianza es un acto de fe en uno mismo",
    "La confianza nos conecta como seres humanos",
    "La confianza es la base del éxito",
    "La confianza siempre encuentra su camino",
    "La confianza transforma vidas",
    "La confianza es una virtud que valoro mucho",
    "La confianza me motiva a seguir adelante",
    }},
        
    {1011011,"resistencia",{
    "Siento resistencia ante los desafíos",
    "La resistencia me da fuerza para seguir adelante",
    "La resistencia crea un ambiente positivo",
    "La resistencia es un acto de perseverancia",
    "La resistencia nos conecta como seres humanos",
    "La resistencia es la base del crecimiento",
    "La resistencia siempre encuentra su camino",
    "La resistencia transforma vidas",
    "La resistencia es una virtud que valoro mucho",
    "La resistencia me motiva a no rendirme",
    }},

    {1011011,"determinacion",{
    "Siento determinacion para alcanzar mis metas",
    "La determinacion me da fuerza para seguir adelante",
    "La determinacion crea un ambiente positivo",
    "La determinacion es un acto de voluntad",
    "La determinacion nos conecta como seres humanos",
    "La determinacion es la base del éxito",
    "La determinacion siempre encuentra su camino",
    "La determinacion transforma vidas",
    "La determinacion es una virtud que valoro mucho",
    "La determinacion me motiva a no rendirme",
    }},
    {1011011, "decision", {
    "Siento seguridad en mis decisiones",
    "La decision me da claridad",
    "La decision crea un ambiente positivo",
    "Tome una decision importante",
    "He tomado una decision importante",
    "La decision que he tomado me hace sentir bien",
    "Tomar una buena decision es fundamental",
    }},

    {1011011,"fortaleza", {
    "Siento fortaleza",
    "Siento fortaleza interior",
    "La fortaleza me da poder",
    "La fortaleza me ayuda a superar obstáculos",
    "La fortaleza crea un ambiente positivo",
    "La fortaleza es un acto de coraje",
    }},
    {1011011,"fuerza", {
    "Siento fuerza",
    "Siento fuerza interior",
    "La fuerza me da poder",
    "La fuerza me ayuda a superar obstáculos",
    "La fuerza crea un ambiente positivo",
    "La fuerza es un acto de coraje",
    }},

    {1010111, "resistencia",{
    "Siento resistencia ante los desafíos",
    "La resistencia me da fuerza para seguir adelante",
    "La resistencia crea un ambiente positivo",
    "La resistencia es un acto de perseverancia",
    "La resistencia nos conecta como seres humanos",
    "La resistencia es la base del crecimiento",
    "La resistencia siempre encuentra su camino",
    "La resistencia transforma vidas",
    "La resistencia es una virtud que valoro mucho",
    "He aprendido a tener resistencia ante las dificultades",
    "La resistencia, forma parte de mi vida",
    "La resistencia me ha permitido superar muchos retos",
    "La resistencia es clave para alcanzar el éxito",
    }},

    {1010111,"perseverancia",{
    "Siento perseverancia",
    "La perseverancia me da fuerza para seguir adelante",
    "La perseverancia crea un ambiente positivo",
    "La perseverancia es un acto de constancia",
    "La perseverancia nos conecta como seres humanos",
    "La perseverancia es la base del éxito",
    "Adoro la perseverancia",
    }},

    {1010111,"tenacidad",{
    "Siento tenacidad",
    "La tenacidad me da fuerza para seguir adelante",
    "La tenacidad crea un ambiente positivo",
    "La tenacidad es un acto de firmeza",
    "La tenacidad nos conecta como seres humanos",
    "La tenacidad es la base del éxito",
    "Adoro la tenacidad",
    "Soy tenaz",
    }},

    {1010111,"resiliencia",{
    "Siento resiliencia",
    "Siempre encuentro resiliencia en los momentos difíciles",
    "La resiliencia me da fuerza para seguir adelante",
    "Hay que tener resiliencia ante los retos",
    "Soy una persona resiliente",
    "La resiliencia es la base del crecimiento",
    "La resiliencia es necesaria para superar obstáculos",
    "La resiliencia me motiva a no rendirme",
    }},

    {1110011,"intriga",{
    "Siento intriga por lo que viene",
    "La intriga me mantiene alerta",
    "La intriga crea un ambiente emocionante",
    "La intriga es un acto de curiosidad",
    "Estoy intrigado por lo que sucederá",
    "Estoy en la intriga de lo que viene",
    }},

    {1110011,"curiosidad",{
    "Siento curiosidad por aprender más",
    "La curiosidad me impulsa a descubrir cosas nuevas",
    "La curiosidad crea un ambiente de aprendizaje",
    "La curiosidad es un acto de exploración",
    "Estoy curioso por saber más",
    "La curiosidad me lleva a lugares inesperados",
    }},

    {1101111,"amor",{
    "Siento amor por esa persona",
    "El amor me llena el corazón",
    "El amor crea un ambiente positivo",
    "El amor es un acto de entrega",
    "El amor nos conecta como seres humanos",
    "El amor es la base de la felicidad",
    "El amor siempre encuentra su camino",
    "El amor transforma vidas",
    "El amor es una virtud que valoro mucho",
    "El amor me motiva a ser mejor",
    "El amor es lo más importante en la vida",
    "El amor todo lo puede",
    "El amor es infinito",
    "El amor es la fuerza más poderosa",
    "El amor es bonito",
    "El amor es maravilloso",
    "El amor es especial",
    "El amor es único",
    "El amor es eterno",
    "El amor es la escencia de la vida",
    "El amor lo conquista todo",
    "El amor nunca falla",
    "El amor es la clave de la felicidad",
    "El amor es la razón de mi existencia",
    "Siento amor",
    }},

    {1101111,"atraccion",{
    "Siento atracción hacia esa persona",
    "La atracción me hace sentir vivo",
    "La atracción crea un ambiente emocionante",
    "La atracción es un acto de conexión",
    "La atracción nos une como seres humanos",
    "La atracción es la base de las relaciones",
    "La atracción siempre encuentra su camino",
    "La atracción transforma vidas",
    "Siento atracción física",
    "Siento atracción emocional",
    "Siento atracción intelectual",
    "La atracción es una virtud que valoro mucho",
    }},

    {1101111,"autonomia",{
    "Siento autonomía",
    "La autonomía me da libertad",
    "La autonomía crea un ambiente positivo",
    "La autonomía es un acto de independencia",
    "La autonomía nos conecta como seres humanos",
    "La autonomía es la base del crecimiento",
    "Adoro la autonomía",
    }},

    {1101111,"independencia",{
    "Siento independencia",
    "La independencia me da fuerza para seguir adelante",
    "La independencia crea un ambiente positivo",
    "La independencia es un acto de libertad",
    "La independencia nos conecta como seres humanos",
    "La independencia es la base del éxito",
    "Adoro la independencia",
    }},

       // Tristeza
    {1000010, "Tristeza",{"me siento triste", "estoy triste", "estoy triste por muchas cosas", "me siento triste por lo que me paso", "me siento triste por todo esto", "estoy triste por todo lo que me esta pasando", "estoy triste por lo que sucedio"}},
    {1000010, "Afliccion",{"me siento afligido", "estoy presentando una afliccion por lo que paso", "estoy afligido por esto", "me afligido por lo que ocurrio", "actualmente estoy afligido", "estoy afligido por todo"}},
    {1000010, "Estado de Desanimo", {"me he sentido ultimamente desanimado", "no tengo muchas ganas de hacer las cosas", "me siento desanimado", "estoy desanimado", "las cosas que me han pasado me tienen desanimado", "no tengo ganas de hacer nada", "no tengo ganas de hacer las cosas", "me siento sin animos", "estoy sin animos para nada"}},
    {1000010, "Desmotivacion", {"estoy desmotivado por las cosas", "me siento desmotivado", "he perdido mi motivacion", "ultimamente he estado desmotivado","estoy desmotivado", "como van las cosas me han desmotivado", "las cosas que he vivido me han desmotivado"}},
    {1000010, "Desasosiego", {"me he sentido desasosegado por mi situacion", "no aguanto en estar desasosiego", "me siento desasosiego por tantas cosas", "el desasosiego me ha afectado mi bienestar", "mi vida esta en desasosiego","me siento desasosegado por mi vida", "estoy desasosegado por mi situacion"}},

    // Frustracion
    {1110000,"Frustracion", {"me gano la frustracion", "la frustracion me esta haciendo daño", "siento frustracion en mi", "estoy frustrado por todo esto", "mi situacion me genera frustracion", "mi frustracion me ha afectado", "me encuentro frustrado", "estoy frustrado por las cosas"}},
    {1110000,"Fracaso", {"he cometido un fracaso", "soy un fracaso", "me siento como un fracasado", "la vida otra vez me recuerda mi fracaso", "soy un fracaso en todo lo que hago", "el fracaso es algo que me acompaña", "me duele fracasar"}},
    {1110000,"Irritacion", {"ultimamente estoy teniendo irritacion", "estoy irritable en este momento", "me siento irritado todo el tiempo", "la irritacion se ha apoderado de mi", "no puedo pensar por esta irritacion", "estar irritado me desgasta","me siento irritado", "me he sentido irritado"}},

    //Arrepentimiento
    {1100100,"Arrepentimiento", {"el arrepentimiento me consume", "estoy arrepentido de lo que hice","estoy arrepentido de lo que paso","me arrepiento de lo que hice", "el arrepentimiento es algo que consume el alma", "estoy arrepentido por mis acciones"}},
    {1100100,"Culpa", {"siento culpa por lo que hice","tengo sentimiento de culpa", "me siento culpable por mis acciones", "la culpa me consume", "me siento culpable por mis acciones pasadas", "la culpa me quita mi paz", "me he sentido culpable", "soy el culpable de mis acciones"}},
    {1100100,"Remordimiento",{"siento remordimiento por mis acciones", "sufro de remordimiento", "siento un remordimiento en mi ser", "siento un remordimiento por mis acciones", "he presentado remordimiento","el remordimiento me esta destruyendo por dentro"}},

    //abrumado
    {1000111,"abrumado",{"estoy abrumado por mi situacion", "la vida me tiene abrumado", "estoy abrumado por lo que paso", "me siento abrumado por lo que ocurrio", "lo que estoy haciendo me esta abrumando", "mi situacion me abruma", "me siento abrumado"}},
    {1000111,"agobio",{"mi situacion actual me agobia","la vida me tiene agobiado", "el agobio me esta consumiendo el alma", "no puedo mas con este agobio", "el estar agobiado me a nublado mi vision", "agobiarme me ha hecho volverme un emjambre", "este agobio me ha quitado mi paz", "agobiarme me esta agotando mentalmente", "este agobio me duele"}},
    {1000111,"angustia",{"mi angustia me prohibe de ver lo bueno de las cosas", "mi angustia se ha apoderado de mi", "la angustia me ha dejado sin dormir", "la angustia no me deja comer","estoy angustiado por mi situacion", "me siento angustiado por mi futuro", "mi situacion es agobiante", "agobiarme me esta haciendo daño", "agobiarme me esta apagando lentamente"}},
    {1000111, "ansiedad", {"tengo ansiedad por mi futuro", "mi ansiedad me esta afectando mentalmente", "la ansiedad me esta haciendo daño", "la ansiedad no me deja pensar", "la ansiedad esta presente todo el tiempo en mi", "la ansiedad me hace imaginar muchos escenarios fatales", "esta ansiedad me hace sobrepensar", "sobrepienso por mi ansiedad", "mis problemas me dan ansiedad", "me da ansiedad expresarme"}},
        
    // depresion.
    {1101101,"Depresion",{"la depresion me ha arrebatado las ganas", "la depresion es un pozo en el cual no veo salida", "estoy condenado a sufrir esta depresion", "la depresion me ha quitado la razon de vivir", "estoy en depresion por todo lo que me ha pasado", "la depresion no me deja disfrutar las cosas","la depresion hace sentirme vacio por dentro", "la depresion me hace encerrarme en mi mismo", "la depresion hace que las personas se alejen", "la depresion me arrebato la razon para vivir"}},
    {1101101,"Vacio",{"siento un vacio en mi interior", "el vacio me consume", "el vacio me duele", "este vacio me esta consumiendo lentamente", "no tengo ganas por este vacio que siento", "este vacio me quito mi esperanza con la vida", "el vacio me esta enloqueciendo", "he estado vacio por dentro ","sentirme vacio me ha quitado los animos por las cosas", "el vacio me hace sentirme sin energias", "el vacio me hace quedarme en el limbo"}},

    //Abandono
    {1001111,"Abandono",{"el abandono me duele", "me siento abandonado", "me han dejado abandonado", "yo estoy abandonado", "el abandono me ha hecho sentirme como un accidente", "me siento en abandono","me han dejado abandonado", "mi familia me ha abandonado en mi peor momento", "me abandonaron en mi peor momento", "siento que el abandono me ha hecho sentir que no valgo"}},
    {1001111,"Ausencia", {"siento la ausencia de mi mismo", "me siento ausente", "siento que estoy ausente en mi vida", "siento que no estoy ausente en nada de lo que hago", "la ausencia de mis seres queridos me rompe", "siento la ausencia de los que amo", "siento que no estoy ausente en cada momento", "siento que mi ausencia me roba la vida"}},
    {1001111,"Desamparo",{"me siento desamparado en esta situacion", "el desamparo se ha apoderado de mi ser", "me han dejado desamparado en mi vida", "vivi situaciones donde me desampararon", "me siento desamparado por lo que vivi", "he estado desamparado por lo que vivi", "en mi peor momento me desampararon","en mi lucha me senti desamparado", "me desampararon en este momento", "el desamparo se siente como un hueco en el corazon"}},
    {1001111, "Desolacion", {"me siento desolado", "en mi futuro veo desolacion", "me han dejado desolado en este momento de mi vida", "me siento desolado por mi situacion", "mi desolacion es lo unico que me acompaña", "aquellos que queria me dejaron desolado", "me estoy hundiendo en mi desolacion","me consumo lentamente en mi desolacion"}},
        
    // cansancio
    {1000100,"Cansancio",{"estoy cansado de mi situacion", "presento cansancio por todo lo que me ha pasado", "el cansancio me consume", "el cansancio me tiene con pocas energias", "el cansancio me esta afectando", "estoy cansado de que todo siga igual", "estoy cansado de solo recibir golpes", "me estoy cansando de vivir", "estoy cansado del dolor", "el cansancio diario me agota mental y fisicamente"}},
    {1000100, "Abatimiento", {"me siento abatido por todo","me encuentro abatido", "la vida me ha abatido", "El abatimiento me ha consumido la energia", "mi situacion me ha dejado abatido", "siento que la vida me quiere ver abatido", "quede abatido despues de vivir problemas en mi vida", "me siento abatido despues de lo que me ocurrio", "el abatimiento me ha hecho morir estando respirando", "mi abatimiento me robo las ganas"}},
    {1000100, "Fatiga", {"quede fatigado de tanto pensar", "me fatiga vivir esa situacion de nuevo", "la fatiga me ha apagado lentamente", "siento fatiga cada vez mas", "la fatiga me esta consumiendo", "la fatiga ha agotado mi mente y mi fisico", "la fatiga me ha quitado las ganas de todo", "me he fatigado por tanto pensar", "me fatiga pensar que sera de mi", "la fatiga me quito las ganas", "me siento fatigado por todo", "estoy fatigado por mi situacion"}},
        
    // Dolor
    {1101001,"Dolor",{"siento un dolor en mi pecho", "me duele mi vida", "estoy experimentando un dolor", "me duele que todo me salga mal", "me duele vivir", "me duele sentir que mi vida se escapa", "siento dolor por mi situacion", "siento dolor por quedarme atras", "me duele ver partir a los que amo","me duele quedarme estancado","siento dolor cuanto todo sale mal", "me duele ver el sufrimiento ajeno", "me duele ver a los que quiero sufrir"}},
    {1101001, "Duelo", {"estoy pasando por un duelo", "estoy en duelo por una partida", "estoy en duelo por una noticia que recibi", "estoy en un duelo conmigo mismo", "el duelo que experimento me ha apagado", "este duelo me esta consumiendo", "me estoy perdiendo en mi duelo", "estoy en duelo por el fallecimiento de un ser querido", "estoy en duelo por la muerte de un ser querido", "me siento en duelo por un fallecimiento", "el duelo me ha quitado lo bueno de la vida"}},
    {1101001, "Derrota", {"me siento derrotado", "mis problemas me han derrotado", "me siento derrotado por todo lo que me ha pasado", "la derrota es un sentimiento que me consume", "la derrota me hizo sentir debil", "la derrota me hizo sentir insuficiente", "la derrota aparecio a pesar de esforzarme", "me siento derrotado a pesar de intentarlo", "la derrota vino cuando cai otra vez", "senti derrota al fallar"}},
    {1101001, "Desaliento",{"me siento desalentado", "el desaliento me consume", "el desaliento me ha quitado las ganas", "siento un desaliento en mi ser","estoy desalentado por mi vida", "tengo desaliento por mi futuro", "el desaliento es algo que me acompaña", "mi situacion actual me desalienta", "mis problemas me desalientan", "llevo un desaliento en mis pasos"}},

    // impotencia
    {1101001, "Impotencia", {"me siento impotente por mi futuro", "me siento impotente con mis problemas", "tengo impotencia porque no pude ayudar", "tengo impotencia porque falle", "me siento impotente ante el futuro", "siento una impotencia en mi ser", "la impotencia me hace sentir que debi haber hecho mas", "la impotencia me hace sentir pude haber hecho mas", "la impotencia me afecta mi percepcion de mi", "mi impotencia me hace sentir inutil"}},
    {1111001, "humillacion", {"la humillacion hace pequeña mi voz", "la humillacion me hace sentir menos", "me siento humillado por lo que me paso", "me senti humillado por lo que vivi", "la humillacion me hace sentir debil", "sentir que me humillaran apago mi brillo", "siento que la humillacion es eterna", "todos me humillan a mi", "siento que todos buscan humillarme", "pase un momento humillante"}},
    
    // pesimismo
    {1100011,"pesimismo", {"me siento pesimista ante el futuro", "el pesimismo hace que vea todo negro", "el pesimismo ha apagado el brillo de mi vida", "el pesimismo es una ventana a la oscuridad", "el pesimismo me esta consumiento", "el pesimismo me consume lentamente", "el pesimismo ha dañado a mi mente", "mi vida se volvio pesimista", "el pesimismo esta acabando conmigo", "ser pesimista me ha alejado de la luz"}},
    {1100011,"negatividad", {"me siento negativo por las cosas que me han pasado", "me siento negativo por mis problemas", "mis problemas me volvieron alguien negativo", "la negatividad me ha hecho mas negro", "la negatividad me ha nublado el futuro", "mi negatividad me ha arrebata mi felicidad", "la negatividad me esta consumiendo mi vida", "me siento negativo ante las cosas", "la negatividad me hizo esperar siempre lo malo", "mi negatividad alejo la luz"}},
    {1100011,"desesperanza", {"siento desesperanza de mi futuro", "me siento desesperanzado de lo que sera de mi", "la desesperanza apago mi brillo", "siento desesperanza por lo que me ocurrio", "siento desesperanza por lo que viene", "la desesperanza me quito la vision", "la desesperanza apago mi positividad", "siento desesperanza por todo", "cada vez siento mas desesperanza", "siento desesperanza por mi vida"}},

    // amargura
    {1101010, "Amargura", {"la amargura apaga mi luz", "siento amargura por las cosas", "me da amargura pensar en algo que me ocurrio", "pensar eso me da amargura", "mi amargura arruino mi feliz", "la amargura me hace detestar las cosas", "siento amargura por la vida", "la amargura envenena el alma", "la amargura me angustia", "senti amargura por lo que me paso", "tengo amargura por lo que vivi","me siento amargo por lo que ocurrio"}},
    {1101010, "Arrogancia", {"me siento arrogante por lo que hice", "la arrogancia me consume", "siento arrogancia por lo que pense", "fue arrogante lo que dije", "fue arrogante lo que pense", "la arrogancia me evito avanzar", "ser arrogante me cerro puertas", "la arrogancia me hizo quedarme atras","ultimamente estoy arrogante", "la arrogancia me hizo mala persona", "la arrogancia me creerme supeior"}},
    {1101010,"Desconfianza", {"siento desconfianza por todo", "me siento desconfiado", "la desconfianza me evita avanzar", "la desconfianza daña mis relaciones", "la desconfianza me ha hecho daño", "siento desconfianza de todo el mundo", "desconfio de lo mas minimo", "evito hablar con los demas por la desocnfianza", "no socializo por desconfiar", "evito amar por desconfiar", "la desconfianza me hace quedarme aca en el mismo lugar"}},
    {1101010, "Decepcion", {"Me siento decepcionado de mi vida", "siento decepcion en mi mismo", "estoy decepcionado de mi", "siento decepcion porque falle", "estoy decepcionado de mis acciones", "estoy decepcionado de todo", "mi vida es decepcionante", "siento que decepcione a todos", "lo que hice me decepciono", "me decepciono lo que ellos hicieron", "me decepciono lo que hizo", "mi vida es un espiral de decepciones", "solo hay decepciones por donde voy", "soy una decepcion para mi familia", " soy una decepcion para todos"}},
    {1101010, "Desconsideracion", {"me siento desconsiderado", "mis acciones del pasado fueron desconsideradas", "fue desconsiderado lo que hice", "fue desconsiderado lo que pense", "lo que dije fue desconsiderado", "desconsidere a las personas que amo", "desconsidere a una persona", "mi desconsideacion me hizo daño", "mi desconsideracion daño a las personas que amo", "mi desconsideracion le hizo daño","La descondisideracion me hizo actuar mal"}},
    {1101010, "Desconsuelo", {"Me han dejado en desconsuelo", "me estoy volviendo loco en mi desconsuelo", "mi familia me dejo en desconsuelo", "ellos no me brindaron consuelo", "el desconsuelo vino por una perdida", "el desconsuelo esta acabando conmigo", "el deconsuelo me agota mentalmente", "me hundo en mi desconsuelo", "el desconsuelo vino por una pelea","me dejaron en desconsuelo", "el desconsuelo me ha quitado las ganas", "el desconsuelo me hace sentir pesado"}},

    //  inseguridad 
    {1011010, "inseguridad", {"me siento inseguro de mi futuro", "me siento inseguro de lo que hago", "siento inseguridad en mi voz", "soy inseguro de mi mismo", "tiemblo por esta inseguridad", "me quedo callado por la inseguridad", "la inseguridad me la llevado a sobrepensar", "estoy inseguro de lo que hice", "estoy inseguro de lo que dije", "la inseguridad me ha hecho callar", "la inseguridad me prohibe vivir"}},

    // Nostalgia
    {1101011, "Nostalgia", {"El pasado me da nostaliga", "siento nostalgia por mi infancia", "la nostalgia me hace perderme en mis recuerdos", "la nostalgia me consume al pensar", "la nostalgia me recuerda lo que ya partio", "la nostalgia me recuerda que todo cambio", "la nostalgia es un arma letal", "la nostalgia esta acabando conmigo", "siento nostalgia de mi pasado", "pasar por un lugar me da nostalgia", "esto que vivi me da nostalgia", "la nostalgia me evita ver lo que puede venir", "siento nostalgia al recordar"}},
    {1101011, "Melancolia", {"me estoy ahogando en la melancolia", "la melancolia me consume", "recordar me vuelven melancolico", "la melancolia esta en en mis pasos", "la melancolia me quita la felicidad", "la melancolina me esta quitando las ganas" ,"la melancolia me prohibe vivir", "la melancolia me esta apagando", "me siento melancolico al recordar", "la melancolia es algo que me evita disfrutar", "la melancolia empeora mi actitud"}},
        
    // apatia
    {1010011, "Apatia", {"siento apatia por todo","ultimamente estoy muy apatico", "la apatia apaga mis dias", "la apatia me evita sentir emocion por las cosas", "la apatia me quito lo bueno de la vida", "siento bajas energias por la apatia", "la apatia me quita el presente", "la apatia me prohibe disfrutar", "la apatia me apaga la vida", "la apatia me quita el interes", "la apatia me quito la motivacion", "la apatia me hace incapaz de hacer cosas", "la apatia me consume"}},
    {1010011, "Asco", {"siento asco por las cosas", "siento asco de lo que hice", "siento asco al recordar", "lo que vi me dio asco", "me da asco lo que vivi", "me da asco lo que me dijeron", "me da asco lo que senti", "el asco es horrible", "siento asco al probar eso", "me genera asco pensar en eso", "todo me da asco", "siento asco de mi mismo", "siento asco de los demas", "mis acciones son un asco"}},
    {1010011, "Desapego", {"me he desapegado de todo", "me he desapegado de las personas que me quieren", "el desapego me hizo quedarme solo", "desapegarme me hizo apagarme", "el desapego me hizo encerrarme", "el desapego me evita tener conexiones", " me he desapegado de mis amigos", "desapegarme me impide vivir", "desapergarme me evita sentir de verdad"}},
    {1010011, "Desamor" ,{"el desamor me ha causado sobrepensamientos", "el desamor me ha roto por dentro", "el desamor me apaga lentamente", "el amor no correspondido me duele", "siento desamor por perder a una amistad", "siento desamor por una ruptura", "el desamor me ha apagado el presente", "el desamor me carcome por dentro", "ilusionarme me hizo caer en el desamor", "el desamor me hizo aislarme"}},
    {1010011, "Desprecio", {"me siento despreciado", "he despreciado a los que quiero", "el desprecio hace que mi brillo se apague", "despreciarlos estuvo mal", "el desprecio es un veneno para el alma", "el desprecio me prohibe agradecer por lo bueno", "el desprecio te quita lo bueno de la vida", "el desprecio es un veneno", "todos me han despreciado", "el desprecio es horrible", "ellos me despreciaron", "me han despreciado"}},
    {1010011, "Desden", {"siento desden por la vida" ,"el desden me hace ver lo malo", " siento desden por los problemas", "siendo desden por esa persona" "siento desden por todo", "siento desden por mi situacion", "siento desden por lo que vi", "siento desden por lo que me hicieron", "siento desden por una amistad", "siento desden por un familiar", "el desden me hace malhumorado", "el desden me hace daño"}},
    {1010011, "Desinteres", {"siento desinteres por las cosas", "tengo desinsteres por lo que me rodea", "el desinteres me hace apagar las posibilidades", "siento desinteres por lo que veo", "siento desinteres por lo que me dicen", "tengo desinsteres por la vida", "siento desinteres por mi futuro", "tengo desinteres por mi presente", "el desinteres es una banda que me ciega", "el desinteres me ha apagado el brillo", "el desinsteres me ha hecho perder emocion por las cosas"}},
    {1010011, "Disgusto", {"siento disgusto por todo", "me disgusta mi situacion", "siento disgusto por vivir", "siento disgusto por lo que vivi", "siento disgusto de mi mismo", "el disgusto me cierra a nuevas posibilidades", "me disgusta que siempre sea lo mismo", "me disgusta mi presente", "me disgusta lo que me paso", "siento disgusto por el futuro", "el disgusto me lleva a cerrarme ante las cosas"}},
    {1010011, "Egoismo", {"el egoismo ha hecho que guarde odio", "mi egoismo le ha hecho daño a los demas", "el egoismo me ha cegado", "soy egoista conmigo mismo", "soy egoista hacia los demas", "soy egoista ante todo", "el egoismo me consume lentamente ", "el egoismo me hace daño", "el egoismo hacia los demas es malo para mi", "el egoismo me ha dañado a mi mismo", "el egoismo hace que me envenene"}},
    {1010011, "Indiferencia",{"la indiferencia me ha quitado el interes", "siento indiferencia por las cosas", "siento indiferencia por lo que me rodea", "siento indiferencia por todo", "siento indiferencia por la vida", "la indiferencia me ha cegado de lo bueno", "la indiferencia me ha desmotivado", "la indiferencia me ha quitado las energias", "la indiferencia me ha apagado", "siento indiferencia por lo que viene", "siento indiferencia por lo que paso"}},

    // Ira
    {1001010, "Ira", {"siento ira hacia mi mismo", "me siento con ira", "la ira me hace ver lo malo", " la ira me nubla al actuar", "la ia me esta haciendo daño", "por la ira actue de mala manera", "la ira me hizo herir sin querer", "la ira me llevo a romperme", "siento ira por lo que me ocurrio", "la ira acabo conmigo", "actuar en ira es como actuar ciego", "la ira me hizo hacerle daño a los que quiero"}},
    {1001010, "Enojo", {"el enojo esta acabando conmigo", "actuar enojado me hizo daño", "actuar enojado daño a los demas", "el enojo me hizo actuar mal", "el enojo me nublo mi vision", "el enojo me hizo actuar sin pensar", "el enojo envenena mi alma", "actue enojado contra ellos", "hice las cosas enojado", "hable de forma enojada", "estoy enojado por lo que ocurrio", "el enojo me destruye"}},
    {1001010, "Furia", {"lo que vivi me da furia", "siento furia en mi ser", "la furia me consumio", "mi furia le hizo daño a los que quiero", "la furia me hizo daño", "la furia me hizo actuar mal", "la furia me hizo gritar", "la furia me hizo romper", "siento furia por lo que vivi", "siento furia por lo que hice", "siento furia por lo que sufri", "siento la furia por mis venas", "vivi algo que me desperto una furia"}},
    {1001010, "Rabia", {"me da rabia recordar eso", "me da rabia vivir esto siempre", "cada vez que lo pienso me da rabia", "estoy lleno de rabia", "la rabia me esta haciendo daño", "actuar con rabia me hizo dañar", "la rabia me hizo actuar de mala manera","la rabia me hizo entrar en conflictos","la rabia cego mi vision", "la rabia envenena mi alma", "me da rabia que no me salgan las cosas", "me da rabia que me traten asi", "me da rabia que me hagan menos"}},
    {1001010, "Rebeldia", {"la rebeldia me llevo a cometer errores", "la rebeldia me hizo daño", "la rebeldia me hizo actuar mal", "tuve un momento de rebeldia", "me volvi rebelde", "la rebeldia me ha afectado", "la rebeldia ha afectado mis relaciones", "la rebeldia nublo mi jucio", "ser rebelde me dio problemas", "el pasado actue rebeldemente", "yo fui rebelde"}},
    {1001010, "indignacion", {"me siento indignado de mi mismo", "siento indignacion por lo que hago", "vivir esto me indigna", "siento indignacion por lo que vi", "senti indignacion por lo que sucedio", "siento indignacion por lo que me hicieron", "me siento indignado de como actuaron", "me indigna lo que hice en el pasado", "siento indignacion de lo que hago", "me da indignacion recordar eso", " me indigna vivir esto siempre"}},
 
    // incapacidad
    {1001010, "Incapacidad", {"me siento incapaz de hacer las cosas", "la incapacidad me prohibe de vivir", "me siento incapaz", "soy incapaz de resolver mis problemas", "la incapacidad me hace sentir debil", "la incapacidad me quita las ganas", "siento que soy incapaz de lograr mis objetivos", "la incapacidad me pone limites", "soy incapaz de valerme por mi mismo", "soy incapaz de hacer algo bien"}},
    {1001010, "Ineptitud", {"todos me dicen que soy inepto", "me siento inepto", "siento la ineptitud que habita en mi", "me dijeron que soy inepto","me siento inepto para hacer mis cosas", "siento que mi ineptitud me frenara", "mi ineptitud me hace fallar", "mi ineptitud me hace sentir que falle", "percibo a mi futuro con ineptitud"}},
    {1001010, "Incompetencia", {"siento que soy incompetente ante los demas", "siento una imcompetencia en mi", "la incompetencia me hace sentir debil", "mis problemas me hacen sentir incompetente", "soy incompetente ante mis amigos", "soy incompetente ante mi familia", "mi vida se siente incompetente", "en mi pasado fui incompetente", "mi incompetencia me llevo a donde estoy hoy", "mi incompetencia me destruyo"}},
    {1001010, "Ineficiencia", {"mis esfuerzos son ineficientes", "me siento ineficiente por lo que hice", "me siento ineficiente porque pude hacerlo mejor", "mi ineficiencia me pesa", "la ineficiencia me dice que lo hice mal", "siento que soy ineficiente", "soy ineficiente ante todo", "soy ineficiente para lograr mis objetivos", "mi presente esta lleno de ineficiencia", "mi ineficiencia ha dañado a otros"}},
    {1001010, "Inutilidad", {"me siento inutil", " me siento inversible", "mi inutilidad me lleva a pensar que soy un error", "me siento como un fallo", "mi inutilidad hace que dañe todo", "mi inutilidad me llevo acometer errores", "mi inutilidad le hace daño a los demas", "todos me dicen que soy inutil", "todos piensan que soy inutil", "me siento inutil ante mis problemas", "me siento inutil por lo que paso"}},
    {1001010, "Torpeza", {"me dicen que soy torpe", "me siento torpe", "hago las cosas con torpeza", "la torpeza es mi segundo nombre", "todos me dicen torpe", "todos me creen torpe", "todo lo que hago sale torpe", "la torpeza me hizo actuar mal", "mi torpeza estropeo las cosas", "las cosas estarian mejor si no fuera por mi torpeza", "mis errores me hacen sentir torpe"}},

    // agravio
    {1001101, "agravio", {"el agravio que cometi estuvo mal", "en mi pasado cometi un agravio", "le hice un agravio a un familiar", "el agravio que cometi le hizo daño", "el agravio es una ofensa para los demas", "sufri un agravio", "el agravio me hizo menos", "cometi un agravio con una persona", "reconozco el agravio que cometi"}},
    {1001101,"abuso",{"sufri un abuso en el pasado", "el abuso es algo que me hizo daño", "el abuso me quebro", "me siento abusado", "ellos abusaron de mi confianza", "el abuso que vivi me duele", "siento que fui abusado por lo que vivi", "ellos abusaron de mi", "alguien abuso de mi", "mi confianza se fue cuando abusaron de mi", "ese abuso me daño eternamente"}},
    {1001101,"agresion",{"me siento agredido", "sufri una agresion", "en el pasado me agredieron", "mi familia me agredio", "todos me agreden", "me siento agredido por lo que sucedio", "me agredieron en mi lugar seguro", "la agresion me hizo daño", "la agresion apago mi brillo"}},
    {1001101,"alteracion",{"me siento alterado", "la alteracion me hace sentir como un volcan", "mi situacion me altera", "vivi algo que me altero", "me altera pensar sobre mi futuro", "mis problemas me alteran", "me paso algo que me altero", "siento alteracion por lo que vivi", " la alteracion me nublo", "mi alteracion me hizo actuar mal", "mi alteracion le hizo daño", "actuar alterado me hizo daño"}},
    {1001101,"destruccion",{" me siento destruido", "recordar mi pasado me destruye", "pensar en mi futuro me destruye", "vivir asi me esta destruyendo", "mis problemas me estan destruyendo", "lo que vivi me destruyo", "un ser querido me destruyo", "un amigo me destruyo", "alguien me destrozo el corazon", "destrui a alguien que quiero"}},

    // traicion
    {1100001, "traicion", {"me siento traicionado", "mis amigos me traicionaron", "mis familiares me traicionaron", "en mi pasado me traicionaron", "me han traicionado", "la traicion me duele", "la traicion me vino por la espalda", "sin pensarlo me traicionaron", "yo cometi una traicion", "me traicione a mi mismo", "traicione a los que queria", "traicione a aquello que amaba"}},
    {1100001, "engaño", {"me siento engañado", "en mi pasado me engañaron", "el engaño hace daño", "el engaño me hizo daño", "me engañe a mi mismo", "el engaño me duele", "engañe a alguien", "el engaño que hice no estuvo bien", "engañe a los que queria", "engañe a alguien importante", "engañe a aquello que ame"}},
    {1100001, "infidelidad", {"me fui infiel a mi mismo", "le fui infiel a mis principios", "alguien me fue infiel", "sufri una infidelidad", " en el pasado me fueron infiel", "cometi una infidelidad", "la infidelidad que hice estuvo mal", "la infidelidad me hizo daño", "le fui infiel a lo que ame", "la infidelidad que cometi no tiene perdon", "le fui infiel a su palabra"}},
    {1100001, "mentira",{"me menti a mi mismo", "le menti a quien queria", "la mentira salio a la luz", "la mentira que dije estuvo mal", "la mentira me hizo daño", "la mentira le hizo daño", "la mentira me consumio", "en el pasado me mintieron", "mi vida esta construida por mentiras", "yo miento por todo", "yo menti por como me sentia", "mis mentiras me condujeron a la decadencia", "mis mentiras me llevaron a donde estoy"}},
    {1100001, "rechazo", {"me han rechazado", "me siento como un rechazado", "mis amigos me rechazaron", "el rechazo me dolio", "todos me rechazan", "mi familia me rechaza", "todo lo que hago es rechazado", "en el pasado fui rechazado", "el rechazo se volvio parte de mi vida", "alguien que me gustaba me rechazo", "mis amigos me rechazaron", "me rechazo por como soy", "el rechazo me hizo esconderme"}},
    {1100001, "perfidia", {"he cometido perfidia contra mis seres queridos","he cometido perfidia con los que amo", "la perfidia que cometi le hizo daño", "la perfidia que cometi daño mi corazon", "la perfidia amargo mi corazon", "la perfidia es un acto de traicion", "actue con perfidia", "en el pasado actue con perfidia", "hoy cometi una perfidia"}},
        

    // aburrimiento
    {1100001, "aburrimiento", {"me siento aburrido por lo que paso", "mi vida es aburrida", "siento aburrimiento por todo", "el aburrimiento me hace actuar de mala manera", "el aburrimiento hace que no disfrute las cosas", "todos me dicen que soy aburrido", "el aburrimiento me consume", "siento que soy aburrido", "el aburrimiento me quita las fuerzas", "la monotonia me aburre", "el aburrimiento me evita ver lo bueno", "me aburre hacer esto siempre"}},
    {1100001, "fastidio", {"siento fastidio por todo", "soy un fastidio", "mis problemas me fastidian", "estoy fastidiado", "me fastidia hacer cosas", "me fastidio facilmente", "siento que fastidio a los demas", "me fastidia mi estilo de vida", "me fastidia vivir esto siempre", "estoy fastidiado de la vida", "me fastidia recordar"}},
    {1100001, "tedio", {"siento tedio por las cosas", "las cosas me producen tedio", "siento tedio por mi pasado", "siento tedio por lo que hago", "mis problemas son tediosos", "mi vida se volvio tediosa", "mis problemas me volvieron tedioso", "siento tedio por aquello que me gustaba","me da tedio recordar", "siento tedio por mi rutina", "la monotonia me es tediosa"}},
    {1100001,"hastio", {"mi vida me llena de hastio", "siento hastio por mis problemas", "siento hastio por pensar en mis problemas", "siento hastio por mi situacion", "el hastio amarga mis dias", "el hastio me quito mis fuerzas", "me da hastio vivir", "me da hastio sentir", "el hastio viene cuando recuerdo", "siento hastio por continuar"}},

    // espanto
    {1101000,"Espanto",{"estoy espantado de lo que vivi", "siento espanto de mi mismo", "el espanto me ha afectado", "siento espanto de lo que me espera", "siento espanto por mi futuro", "siento espanto de la incertidumbre", "el espanto me ha consumido la mente", "me siento espantado de lo que estoy viviendo", "soy un espanto para todos", "yo soy un espanto"}},
    {1101000, "Miedo", {"tengo miedo de mi futuro", "tengo miedo de mi mismo", "me dan miedo mis problemas", "me da miedo perderme", "me da miedo el que vuelva a vivir esa situacion", "el miedo me encadena", "el miedo me limita a hacer cosas", "me da miedo hacer algo nuevo", "me da miedo actuar", "me da miedo decir lo que siento", "me da miedo expresar lo que siento", "siento miedo de mi pasado", "siento miedo por mi futuro"}},
    {1101000, "Terror", {"siento terror por todo", "siento terror por mis problemas", "siento terror al recordar mi pasado", "siento terror por el futuro", "el terror me hace quedarme en el mismo lugar", "siento terror por lo desconocido", "siento terror por lo que vivi", "vivi una situacion de terror"}},
    {1101000, "Panico", {"siento panico por lo que vivi", "siento panico por mi futuro", "estoy viviendo una situacion de panico", "el panico me consume", "el panico me ha hecho daño", "me ha afectado esta situacion de panico", "el panico me hizo actuar diferente", "siento panico al recordar mis traumas", "el panico se apodero de mi"}},
    {1101000, "Fobia", {"me dio un ataque de fobia", "la fobia me hizo actuar diferente", "la fobia se apodero de mi cuerpo", "la fobia hace que me aleje de cosas", "mi fobia me hace asustarme", "la fobia me hace temblar", "tengo fobia hacia lo que me paso", "recordar eso me da fobia", "me da fobia sobrepensar", "me da fobia"}},
   
    // injusticia
    {1101000, "Injusticia", {"mi pasado esta lleno de injusticias", "a pesar de esforzarme sufri una injusticia", "perdi contra una injusticia", "la injusticia me da coraje", "me siento debil por esta injusticia", "esta injusticia me hizo sentir debil", "esta injusticia me hizo sentir coraje", "siento injusticia por lo que me hicieron", "siento injusticia en mi vida", "mi vida tiene muchas injusticias"}},
        
    // insatisfaccion
    {1010110, "Insatisfaccion", {"me siento insatisfecho por mi vida", "me siento insatisfecho por lo que hago", "mi vida esta llena de insatisfaccion", "estoy insatisfecho de mis acciones", "siento insatisfaccion por mi pasado", "la insatisfaccion me ha quitado la energia", "siento insatisfaccion por lo que me gusta", "mi vida esta llena de insatisfacciones", "la insatifaccion me ha robado la felicidad"}},
    {1011000, "insuficiente", {"me siento insuficiente", "siento que mis acciones son insuficientes", "lo que hago es insuficiente", "todos me dicen que soy insuficiente", "me hacen sentir insuficiente", "mi insuficiencia me desmotiva", "cuando me dicen insuficiente me quiebro", "me duele ser insuficiente", "la insuficiencia me acompaña en mis pasos","en el pasado fui insuficiente"}},
    {1011000, "inconformidad", {"me siento inconforme", "la inconformidad me evita aceptarme", "siento inconformidad por lo que quiero", "me inconforma mi presente", "siento inconformidad por lo que hago", "la inconformidad me quita la felicidad", "me siento inconforme de mi mismo", "la inconformidad no me deja aceptar", "mi inconformidad no se va", "veo a los demas y me siento inconforme"}},


    // impaciencia
    {1010000,"impaciencia",{"me siento impaciente", "todos me dicen que soy impaciente", "la impaciencia me hace desesperarme", "la impaciencia me quita mi paz", "la impaciencia me hace pedir todo rapido", "la impaciencia evita que disfrute el tiempo", "la impaciencia me quita mi vida", "la impaciencia me ha llevado a actuar mal", "me siento impaciente por esta situacion", "mi futuro me impacienta", "en el pasado fui impaciente", "yo antes era impaciente"}},

    // insatisfaccion
    {1010110, "insatisfaccion", {"me siento insatisfecho", "me siento insatisfecho de mis logros", "mi insatisfaccion no acaba", "lo hice pero no estoy satisfecho", "mi vida esta llena de insatisfaccion", "la insatisfaccion me impide  vivir", "siento insatisfaccion por mi presente", "la insatisfaccion se ha apoderado de mi", "me siento insatisfecho por lo que hago", "mi insatisfaccion me prohibe disfrutar lo que hago"}},
    {1010110, "pereza", {"me siento con pereza", "la pereza me tiene mal", "la pereza apago mis energias", "me siento con pereza", "esta pereza apago mi brillo", "siento pereza al hacer algo", "siento pereza por todo", "mi pereza me consume", "me dicen que tengo pereza", "mi pereza me quito las ganas", "soy perezoso", "mi pereza me quito las ganas de levantarme","siento pereza por mi presente","siento pereza por lo que hago"}},
    {1010110, "flojera", {"tengo flojera por las cosas", "me siento con flojera", "la flojera me consume", "me dicen que tengo flojera", "me da flojera hacer las cosas", "siento flojera por todo", "la flojera me evita disfrutar las cosas", "la flojera me evita empezar las cosas", "no empiezo las cosas por flojera", "la flojera me evita conocer cosas nuevas", "siento flojera por lo que hago"}},
    {1010110, "procrastinacion",{"la procrastinacion hace que no quiera hacer nada", "la procrastinacion hace que posponga mis cosas", "la procrastinacion ha afectado mi desempeño", "me he vuelto procrastinador", "en el pasado procrastine mucho", "estoy procrastinando", "me dicen que procrastino", "procrastinar me ha hecho quedarme atras", "procrastinar me hizo daño", "procrastinar me hizo perder oportunidades", "perdi cosas por procrastinar", "procrastine por miedo", "dejo todo de ultimo", "retraso las tareas importantes"}},

    // impertubabilidad
    {1010010, "impertubabilidad",{"me siento imperturbado por mis problemas", "la impertubabilidad me hace sentir libre", "me siento imperturbado", "la impertubabilidad me hace sentir tranquilo", "cuando recuerdo me siento imperturbado", "la imperburbabilidad me da paz", "enfrente a mis problemas imperturbado", "estoy impertubardo con mi situacion actual", "me siento imperturbado por mi futuro", "me mantuve imperturbado al discutir", "me senti imperturvado al actuar"}},

    // discordia
    {1110001, "discordia", {"tuve discordia conmigo mismo", "vivi una situacion de discordia", "tuve una discordia con mis seres queridos", "estoy en discordia con mi pasado", "estoy en discordia con mis problemas", "la discordia me quita la paz", "la discordia me no conformarme", "estoy en discordia con mi presente", "mi discordia me llevo a no perdonar", "mi discordia me cego", "la discordia me hizo actuar mal"}},
    {1110001, "desacuerdo", {"estoy en desacuerdo por lo que hice", "me siento en desacuerdo por lo que vivi", "estoy en desacuerdo con mi situacion", "el desacuerdo me hace no conformarme", " el desacuerdo me hace no aceptar", "estoy en desacuerdo con mi familia", "estoy en desacuerdo por lo que me dicen", "estoy en desacuerdo por lo que me dijeron", "me siento en desacuerdo por el camino que sigo", "estoy en desacuerdo por como soy"}},
    {1110001, "desencanto", {"me siento desencantado por lo que vivi", "me desencanta pasar por esto", "me siento desencanto por mi situacion", "recordar me hace sentir desencantado", "me siento desencantado por mi futuro", "mis acciones me hacen sentir desencantado", "me desencanto lo que vi", "me siento desencantado por lo que me hicieron", "me siento desencantado por las cosas", "me siento desencantado con mis sueños", "me siento desencantado por todo"}},
    {1110001, "desilusion", {"me siento desilusionado por todo", "me siento desilucionado por las cosas", "siento desilusion por lo que hago", "me siento lleno de desilusiones", "siento desilusion por mi futuro", "la vida me ha desilusionado", "mi familia me ha desilusionado", "todos me han desilusionado", "he sentido desilusion por lo que amaba", "la desilucion me ha apagado el alma", "siento una desilusion en mi pecho"}},

    // when eres terco arrogante, obtinado, rigido duro
    {1001001, "terquedad",{"mi terquedad me prohibe comprender a los demas", "mi terquedad me prohibe ver mis errores", "me siento terco por lo que hice", "mi terquedad me evito recibir ayuda", "mi terquedad hizo que me cerrara","mis acciones fueron tercas", "en mi pasado era terco", "me he vuelto terco", "cometi un error por terco", "cometi varios errores por terco", "mi terquedad me hizo hundirme", "me pasaron las cosas por terco", "ser terco me hizo ignorante hacia la vida"}, {"mi terquedad me llevo a donde estoy hoy"}},
    {1001011,"obstinacion", {"siento obstinacion por mis problemas", "me siento obstinado por lo que me paso", "la obstinacion me hizo actuar mal", "dicen que soy obstinado", "mi obstinacion amargo mi dia", "me obstinan mis problemas", "la vida me tiene obstinado", "me obstine por lo que me paso", "me obstine porque cometi errores", "me obstine cuando me entere", "la obstinacion me hace no avanzar", "mi obstinacion le hizo daño"}},
    {1001011, "rigidez", {"me he vuelto rigido con el tiempo", "en el pasado fui rigido", "me dicen que soy rigido", "mi rigidez no me deja aprender", "mi rigidez no me deja aceptar puntos de vista diferentes", "mi rigidez me hizo cerrarme", "mi rigidez no me permite evolucionar", "me vuelvo rigido al interactuar", "mi rigidez me hizo quedarme atraz", "me puse rigido en esa situacion", "mi rigidez me hizo daño", "mi rigidez le hizo daño a los demas"}},
    {1001011, "ignorancia", {"me he vuelto ignorante", "mi ignorancia me hizo quedarme atras", "mi ignorancia me hizo daño", "mi ignorancia me cego", "en mi pasado fui ignorante", "me dicen que soy ignorante", "me siento ignorante","mis pensamientos son ignorantes", "estoy viviendo de manera ignorante", "mi ignorancia me hizo cometer errores", "mi ignorancia me hizo no avanzar", "mi ignorancia fue mi punto de partida", "ser ignorante me destruyo"}},
    {1001011, "inflexibilidad", {"mi inflexibilidad me hizo no avanzar", "me dicen que soy inflexible", "me siento inflexible", "ser inflexible me hizo no aprender", "la inflexibilidad no me dejo ver mis errores", "actuo inflexible contra los demas", "mis acciones son inflexibles","mi pensamientos son inflexibles", "mi inflexibilidad me hizo daño", "mi inflexibilidad le hizo daño a los demas", "ser inflexible no me dejo ver lo malo en mi"}},

    // confusion
    {1000110, "confusion", {"me siento confundido por lo que siento", "lo que vivi me confundio", "me siento confundido de mi mismo", "me confundo facilmente siempre", "me confunde las acciones de los demas", "confundirme me hizo reflexionar de lo que hago", "me siento confusion por lo que soy", "mi situacion actual me confunde", "me confundi por lo que me paso", "siento confusion en mi camino", "mi confusion me hace sentir perdido","mi confusion es reflejo de lo que no se"}},
    {1000110, "duda", {"dudo de mis capacidades", "dudo de lo que hago", "mi duda me evita avanzar", "siento dudas de lo que soy capaz", "siento dudas de mi mismo", "dudo de mis acciones", "dudar me hizo perderme, pero tambien encontrarme", "mi mente esta llena de dudas", "no hablo porque dudo", "no me abro con los demas porque dudo", "me siento dudoso de mi futuro", "dudar me hace pensar de mas"}},
    {1000110, "incertidumbre", {"siento incertidumbre de mi futuro", "mis pensamientos me generan incertidumbre","me da incertidumbres mis problemas", "siento incertidumbre de que sera de mi", "me da incertidumbre pensar en situacion actual", "siento incertidumbre de lo que sueño", "siento incertidumbre de mis metas", "siento incertidumbre por lo que sucedio", "la incertidumbre me hace sobrepensar"}},
    {1000110, "desconcierto", {"me siento desconcertado de lo que me paso", "mis problemas me dejan desconcertado", "el desconcierto me dejo en shock", "mis acciones me dejaron desconcertaron", "siento desconcierto de lo que presencie", "esta situacion me desconcerto", "me siento desconcertado por lo que viene", "mi desconcierto vino por una noticia", "me desconcierta lo que me contaron", "me desconcierta lo que me hicieron"}},
    {1000110, "desorientacion", {"me siento desorientado con lo que hago", "quede desorientado por lo que vivi", "me dejaron desorientado", "me siento desorientado con mi vida", "una noticia que recibi me desoriento", "mis pasos son desorientados", "mis problemas de desorientan", "me siento desorientado con mi futuro", "me siento desorientado en lo que hago", "mis pensamientos me desorientan"}},
    {1000110, "inquietud", {"me siento inquieto por lo que vivi", "me inquietan mis problemas", "siento inquietud por mi futuro", "esta situacion me inquieta", "me inquieta no saber que sera de mi", "mi pasado me inquieta", "me siento inquieto todo el tiempo","la inquietud me hace temblar", "me inquieta pensar en las cosas", "me inquieto cuando recuerdo eso", "me inquieta no saber que sera de mi futuro"}},
    
    // dependencia emocional ohno :c
    {1100110, "apego", {"el apego bajo mi valor", "mi apego me cego", "estoy apegado a una persona", "mi apego me hizo descuidarme", "mi apego me hizo conformarme con poco", "mi apego me hizo que no viera mi valor", "mi apego me hizo creer que merecia menos", "mi apego me hizo daño", "mi apego me hizo cometer errores", "mi apego me hizo tolerar cosas que no debi"}},
    {1100110, "dependencia", {"mi dependencia se ha vuerto dañina", "la dependencia me hizo no ver mi valor", "la dependencia me hizo quedarme donde no me querian", "mi dependencia me hizo daño", "depender de alguien me hizo perderme", "la dependencia me hace sentir miedo al abandono", "la dependencia me hizo actuar por lo que esperaban de mi", "mi dependencia me hizo conformarme con poco"}},

    // resentimiento 
    {1001110, "resentimiento",{"siento resentimiento hacia una persona", "siento resentimiento por mi pasado", "esta situacion me da resentimiento", "mi resentimiento no me deja perdonar", "mi resentimiento no me deja avanzar","para dejar mi resentimiento tengo que perdonar", "siento resentimiento por mis acciones", "tengo guardado resentimiento en mi corazon", "sentir resentimiento me esta dañando", "mi resentimiento me esta cegando"}},
    {1001110, "repudio",{"siento repudio hacia todo", "siento repudio hacia alguien", "siento repudio hacia mi situacion", "me repudia vivir esto", "me repudia lo que me hicieron", "siento repudio de mis acciones", "me repudia recordar el pasado", "el repudio me hizo malo", "repudiar me quito hizo no perdonar", "repudiar me hizo quedarme estancado", "el repudio me hizo odiar a los demas", "siento repudio por lo que soy"}},
    {1001110, "rencor",{"siento rencor por mi pasado", "siento rencor hacia una persona", "el rencor no me permite vivir", "el rencor no me permite perdonar", "mi rengor me ha hecho quedarme atras", "mi rencor me ha hecho actuar mal", "siento rencor por mis acciones", "el rencor me hizo daño", "mi rencor le hizo daño a los demas", "mi rencor me ha cegado", "me consume este rencor que acumulo", "siento rencor por una traicion"}}
};